[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
iced = "0.9.0"
reqwest = { version = "0.11.17", features = ["blocking", "json", "cookie_store"] }
common_structs = { version = "0.1.0", path = "../common_structs" }
